"""Adversarial S-Box research package."""

from .cryptoshield import (
    algebraic_degree,
    differential_distribution_table,
    differential_uniformity,
    improved_transparency_order,
    is_bijective,
    linear_approximation_table,
    max_linear_correlation,
    nonlinearity,
    sac_score,
    validate_sbox,
)
from .datasets import PairSample, generate_balanced_pairs, split_dataset
from .evolution import (
    ClassicalMetrics,
    EvolutionConfig,
    EvolutionResult,
    HardConstraints,
    classical_rank,
    equivalent_random_budget,
    evaluate_classical,
    evolve_permutations,
    is_admissible,
    make_classical_evaluator,
    ordered_crossover,
    random_search,
    random_sbox,
    swap_mutation,
)
from .provenance import fingerprint_dataset, fingerprint_sbox
from .spn import ToySPN

__all__ = [
    "ClassicalMetrics",
    "EvolutionConfig",
    "EvolutionResult",
    "HardConstraints",
    "PairSample",
    "ToySPN",
    "algebraic_degree",
    "classical_rank",
    "differential_distribution_table",
    "differential_uniformity",
    "equivalent_random_budget",
    "evaluate_classical",
    "evolve_permutations",
    "fingerprint_dataset",
    "fingerprint_sbox",
    "generate_balanced_pairs",
    "improved_transparency_order",
    "is_admissible",
    "is_bijective",
    "linear_approximation_table",
    "make_classical_evaluator",
    "max_linear_correlation",
    "nonlinearity",
    "ordered_crossover",
    "random_search",
    "random_sbox",
    "sac_score",
    "split_dataset",
    "swap_mutation",
    "validate_sbox",
]
